### ISSUE TITLE
custom install nvim-treesitter breaks theme on a .go file

### ISSUE THREAD

**Issue by nkk1** [NvChad/starter#18]
If I add nvim-treesitter at ~/.config/nvim/lua/plugins/init.lua with my configs, it breaks the theme.  ie everytime I have to <leader>th and select the theme.
```
{
    "nvim-treesitter/nvim-treesitter",
    config = function()
      require("nvim-treesitter.configs").setup {
        ensure_installed = {
          "go",
        },
      }
    end,
  },
```

I see that nvim-treesitter is already installed by NvChad. Is it possible to add my custom configs to the existing one? 

If I add "nvim-treesitter/nvim-treesitter-textobjects" it breaks the theme as well. 

I do see the theme getting updated in chardrc.lua file 

```
M.ui = {
  theme = "ashes",
```

**Comment by siduck** [comment]
show what u mean by theme break, pls make a video or pic

**Comment by olafmustafar** [comment]
Hi, I believe the same thing is happening on my end after I switched to nvchad 2.5. But with the plugin  ```{ "Eandrju/cellular-automaton.nvim" , lazy=false},``` instead of tree-sitter


#<details><summary>Here is a comparison:  </summary>
![image](https://github.com/NvChad/starter/assets/42854638/4cea49ae-76c3-4de4-bc2c-0fb7a9ee0e92)
![image](https://github.com/NvChad/starter/assets/42854638/61c8ec2f-3fb6-429f-86d9-a48c4fb1826e)
#</details>

**Comment by siduck** [comment]
your code isnt even loading the default hlgroups of treesitter from base46 :/

**Comment by siduck** [comment]
![image](https://github.com/NvChad/starter/assets/59060246/97127b56-df9b-4dab-9ec5-962f825593e5)

you do know that lazy.nvim doesnt merge "functions"? so please  copy the default code from config func and then add your code  below it
